### ISSUE TITLE
Rename option "leave" to "move"? 

### ISSUE THREAD

**Issue by JamesJDillon** [microwaveabletoaster/dunces-and-dungeons#17]
On first play-through I got quite confused as I thought "leave" suggested actually leaving the dungeon instead of just leaving the room. Maybe replacing it with "move" would be more intuitive?

**Comment by CameronEgger** [comment]
Thank you very much for the suggestion! Will work on fixing this soon. Will also work on uploading a newer version sometime in the next week with a load of bug fixes and new features!
